### ISSUE TITLE
assertion: "from->thread_delayed_free == NULL" triggered during heap deletion

### ISSUE THREAD

**Issue by colesbury** [microsoft/mimalloc#204]
Somewhat related to #202. This can trigger when an allocation a one non-backing heap is freed while that heap is being deleted. Below is a program that reproduces this behavior when an artificial sleep is introduced in mi_heap_absorb.

Note that the allocation `p` outlives the heap from which it was allocated.

Program:

```c
#include <thread>
#include <mimalloc.h>
#include <unistd.h>

volatile void* p;

void t1main() {
    mi_heap_t* heap = mi_heap_new();
    p = mi_heap_malloc(heap, 1024);
    mi_heap_delete(heap);
}


int main() {
    auto t1 = std::thread(t1main);

    usleep(1000 * 150);
    assert(p);
    mi_free((void *)p);

    t1.join();
}
```

heap.c diff to cause the free to happen between `_mi_heap_delayed_free` and assertion.

```diff
 #include "mimalloc-atomic.h"

 #include <string.h>  // memset, memcpy
+#include <unistd.h>


 /* -----------------------------------------------------------
@@ -324,6 +325,8 @@ static void mi_heap_absorb(mi_heap_t* heap, mi_heap_t* from) {
   // free outstanding thread delayed free blocks
   _mi_heap_delayed_free(from);

+  usleep(1000 * 300);
+
   // transfer all pages by appending the queues; this will set
   // a new heap field which is ok as all pages are unfull'd and thus
   // other threads won't access this field anymore (see `mi_free_block_mt`)
```

**Comment by daanx** [comment]
Hi Sam, thanks again; I think this is indeed expected by the current design -- I commented in #202 for how we can perhaps improve on the current implementation.

**Comment by colesbury** [comment]
@daanx, can you re-visit this? I don't think this is the same as #202. In this issue the **allocation** out lives the thread. The documentation and code all seem to suggest that this is supported. For example, `mi_heap_delete()` says:

> This will release resources and migrate any still allocated blocks in this heap (efficienty) to the default heap.

**Comment by daanx** [comment]
@colesbury, yes you are right -- this should work; was thinking of `mi_heap_destroy`... I will look at it again and at your possible fix. I believe I should probably implement the `local` model as that is what the documentation implies as well.

**Comment by daanx** [comment]
Hi Sam; I think I fixed this issue -- the heap absorb was just wrong (out of date). Hope this works for you. Still considering how to handle #202 better ...

**Comment by colesbury** [comment]
Here are the additional usleeps (on the `dev` branch 946a71c): https://gist.github.com/colesbury/f3487f9d4f89dbf3497bcff2ca454458

**Comment by daanx** [comment]
Ah, it is indeed not quite correct yet! We cannot call `mi_heap_page_never_delayed_free` as that could cause the page to never be freed. It works for abandoned pages as those get checked on reclamation if all blocks are free at that point. Since we absorb directly into a new heap here that is not the case now. 
I see how to fix it though... we should wait before updating the new heap pointer in the page queues if it happens to be delayed_freeing at that time.

**Comment by daanx** [comment]
.. I think this should be right now. I like the sleeps that you added -- I will think of adding these at strategic places to enable better debugging of these concurrency errors.

**Comment by colesbury** [comment]
Hi Daan, I'm still seeing assertion failures with the most recent change. (Same test script and same usleep calls). I'm on 67de254 so I think it includes the most recent fixes.

```
mimalloc: assertion failed: at "/Users/sgross/Projects/mimalloc/include/mimalloc-internal.h":455, mi_page_set_heap
  assertion: "mi_page_thread_free_flag(page) != MI_DELAYED_FREEING"
```

**Comment by daanx** [comment]
Hi Sam, ah right, in this case the assertion is wrong -- at the absorb time it is ok to be delayed freeing at that point; I will update that. Thanks!

**Comment by daanx** [comment]
Hope this fixes the issue. Thanks for your help getting this right :-)

**Comment by colesbury** [comment]
Thanks, that seemed to fix the issue.
